# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml

analyzer:
#   exclude:
#     - path/to/excluded/files/**

# Jaspr has a custom analyzer plugin 'jaspr_lints', which is enabled here.
#
# You can toggle Jaspr specific lint rules in the 'diagnostics' section below.
plugins:
  jaspr_lints:
    version: ^0.6.0
    diagnostics:
      prefer_html_components: true
      sort_children_last: true
      styles_ordering: true

# Uncomment the following section to enable or disable additional rules.

linter:
  rules:
    public_member_api_docs: false
    prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
formatter:
  trailing_commas: preserve
  page_width: 260

