/// The entrypoint for the **server** environment.
///
/// The [main] method will only be executed on the server during pre-rendering.
/// To run code on the client, check the `main.client.dart` file.
library;

import 'package:jaspr/dom.dart';
// Server-specific Jaspr import.
import 'package:jaspr/server.dart';

// Imports the [App] component.
import 'app.dart';

// This file is generated automatically by Jaspr, do not remove or edit.
import 'main.server.options.dart';

void main() {
  // Initializes the server environment with the generated default options.
  Jaspr.initializeApp(
    options: defaultServerOptions,
  );

  // Starts the app.
  //
  // [Document] renders the root document structure (<html>, <head> and <body>)
  // with the provided parameters and components.
  runApp(
    Document(
      title: 'JSON to Dart Converter | Dart Mappable',
      head: [
        const meta(name: 'description', content: 'The most powerful and user-friendly JSON to Dart converter built with Jaspr and Dart Mappable. Generate type-safe Dart classes from JSON with ease.'),
        const meta(attributes: {'property': 'og:title'}, content: 'JSON to Dart Converter | Dart Mappable'),
        const meta(attributes: {'property': 'og:description'}, content: 'Generate type-safe Dart classes from JSON using Dart Mappable and Jaspr.'),
        const meta(attributes: {'property': 'og:url'}, content: 'https://jsondart.shreeman.dev'),
        const meta(attributes: {'property': 'og:type'}, content: 'website'),
        const link(rel: 'canonical', href: 'https://jsondart.shreeman.dev'),

        // Link the styles.css file, this will be generated by the tailwind integration.
        const link(href: 'styles.css', rel: 'stylesheet'),
        // Add highlight.js for syntax highlighting
        const link(href: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/atom-one-dark.min.css', rel: 'stylesheet'),
        const script(src: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js'),
        const script(src: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/dart.min.js'),
        const script(src: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/json.min.js'),
        const script(src: 'https://cdnjs.cloudflare.com/ajax/libs/highlightjs-line-numbers.js/2.9.0/highlightjs-line-numbers.min.js'),
      ],
      styles: [
        // Special import rule to include to another css file.
        css.import('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap'),
        // Each style rule takes a valid css selector and a set of styles.
        // Styles are defined using type-safe css bindings and can be freely chained and nested.
        css('html, body').styles(
          width: 100.percent,
          minHeight: 100.vh,
          padding: .zero,
          margin: .zero,
          fontFamily: const .list([FontFamily('Inter'), FontFamilies.sansSerif]),
        ),

        // Highlight.js line numbers styles for better spacing
        css('.hljs-ln-numbers').styles(
          raw: {
            'text-align': 'right',
            'color': '#64748b',
            'border-right': '0px solid #e2e8f0',
            'padding-right': '12px',
            'margin-right': '12px',
            'user-select': 'none',
            'width': '40px',
            'display': 'inline-block',
          },
        ),
        css('.hljs-ln-code').styles(
          raw: {
            'padding-left': '8px',
          },
        ),
      ],
      body: const App(),
    ),
  );
}
